dcibaseresource: Fix py34 incompatibility
Test are working on py27 but not py34 when implementing a resource this
is because kwargs.iteritems() is not working on py34 leading to

E       AttributeError: 'dict' object has no attribute 'iteritems'

This fixes it.

Change-Id: I9aabab91a3e3cce3fb05ae758718c0a8173045a3